### PR TITLE
Fix Project search AutoComplete

### LINKED ISSUE #327: Project-search autocomplete in 'Merge Projects' modal does not return results
This autocomplete should provide sync search functionality, but seems to be broken at the moment.

Screenshot 2024-10-27 at 7 35 59 PM

### PR DESCRIPTION
**Pull request by ri-pandey**
**Description**

Fixed Project search AutoComplete.

**Related Issue(s)**

Closes #327 

**Changes Made**

List the main changes made in this PR. Be as specific as possible.

- [ ] Feature added
- [x] Bug fixed
- [x] Code refactored
- [x] Tests changed
- [x] Documentation updated
- [ ] Other changes: [describe]

**Screenshots (if applicable)**

project-merge

**Checklist**

Before submitting this PR, please make sure that:

- [x] Your code passes linting and coding style checks.
- [x] Documentation has been updated to reflect the changes.
- [x] You have reviewed your own code and resolved any merge conflicts.
- [x] You have requested a review from at least one team member.
- [x] Any relevant issue(s) have been linked to this PR.

### CODE REVIEW

File: ui/src/components/project/ProjectSelect.vue [hunk 1]
```diff
@@ -43,7 +44,7 @@ const searchText = ref("");
 const projects = ref([]);
 
 projectService.getAll({ forSelf: false }).then((res) => {
-  projects.value = (res.data || []).filter(
+  projects.value = (res.data.projects || []).filter(
```
Comment (ri-pandey) [inline ui/src/components/project/ProjectSelect.vue:47]: This is the actual fix. Everything else is writing/refactoring e2e tests.

**Review by deepakduggirala — APPROVED** [review]
